FROM debian:stable-slim AS jdsp4linux

ARG DEBIAN_FRONTEND=noninteractive
ENV NODE_ENV=production
ARG TARGETARCH
ENV TZ=UTC

WORKDIR /jdsp4linux

RUN <<EOF
apt update
apt install -y build-essential qt6-qpa-plugins libarchive-dev \
  qt6-base-private-dev qtbase5-private-dev qt6-base-dev libqt6svg6-dev \
  libglibmm-2.4-dev libglib2.0-dev libpipewire-0.3-dev \
  qttools5-dev-tools libgl-dev git

git clone --recursive https://github.com/Audio4Linux/JDSP4Linux
cd JDSP4Linux
mkdir build
cd build
EOF

RUN <<EOF
mkdir -p /jdsp4linux/JDSP4Linux/build
cd /jdsp4linux/JDSP4Linux/build
qmake ../JDSP4Linux.pro CONFIG+=HEADLESS
make -j4
cp ./src/jamesdsp /usr/local/bin
chmod 755 /usr/local/bin/jamesdsp
EOF
