services:
  pipewire:
    extra_hosts:
      - pipewire:127.0.0.1
    network_mode: host
    build:
      context: .
      network: host
      dockerfile: ./Dockerfile
#    volumes:
#      - ./tmp:/transfer
    environment:
      - TZ=Europe/London
      - MEMCACHE=true
    container_name: pipewire
    hostname: pipewire
    restart: unless-stopped
    devices:
      - /dev/snd:/dev/snd:rw
    privileged: true

